-- =============================================
-- SIMPRO CUSTOMER IMPORT
-- 128 customers imported from SimPro
-- Skipped: Test Customer, mellerick test, Mellerick,
--          Mellerick Plumbing Pty Ltd, Mellerick Pty Ltd, Miscellaneous
-- =============================================

INSERT INTO customers (name, company, is_active) VALUES
('Granvue Homes', 'Granvue Homes', true),
('Christmas Hills Primary School', 'Christmas Hills Primary School', true),
('Envisage Group', 'Envisage Group', true),
('Cumberland Project Management Pty Ltd', 'Cumberland Project Management Pty Ltd', true),
('2Construct', '2Construct', true),
('Clark Cranes', 'Clark Cranes', true),
('Brad Foster', 'Brad Foster', true),
('APM Group', 'APM Group', true),
('Daisy Hill Breeding', 'Daisy Hill Breeding', true),
('John Bas', null, true),
('Adam & Sons Excavations', 'Adam & Sons Excavations', true),
('Anytime Fitness Greensborough', 'Anytime Fitness Greensborough', true),
('Matt From Billings', null, true),
('Glenvill Projects', 'Glenvill Projects', true),
('Domain Concrete', 'Domain Concrete', true),
('Glenrich Builders', 'Glenrich Builders', true),
('F.Wood & Sons', 'F.Wood & Sons', true),
('Michael Gliddon', null, true),
('Bowden Corporation', 'Bowden Corporation', true),
('Becon Constructions', 'Becon Constructions', true),
('Happy L Group Pty Ltd', 'Happy L Group Pty Ltd', true),
('Burbank Australia Pty Ltd', 'Burbank Australia Pty Ltd', true),
('Caddy''s Plumbing Pty Ltd', 'Caddy''s Plumbing Pty Ltd', true),
('Cylinder Head Innovations', 'Cylinder Head Innovations', true),
('Harpreet Bajwa', 'Harpreet Bajwa', true),
('Anderson Homes Pty Ltd', 'Anderson Homes Pty Ltd', true),
('DI-LEE Building & Maintenance Pty Ltd', 'DI-LEE Building & Maintenance Pty Ltd', true),
('Figurehead Constructions', 'Figurehead Constructions', true),
('Conundrum Holdings Pty Ltd', 'Conundrum Holdings Pty Ltd', true),
('Apartment Living Melbourne', 'Apartment Living Melbourne', true),
('Hewish Building', 'Hewish Building', true),
('Down to Earth Excavations', 'Down to Earth Excavations', true),
('George E Apted & Associates Pty Ltd', 'George E Apted & Associates Pty Ltd', true),
('Doreen Primary School', 'Doreen Primary School', true),
('Simon Burgess', null, true),
('John Bass', null, true),
('Gravias', 'Gravias', true),
('GMC Resources Pty Ltd', 'GMC Resources Pty Ltd', true),
('Dean Homes', 'Dean Homes', true),
('Aqua Tap Plumbing', 'Aqua Tap Plumbing', true),
('Henley Arch Pty Ltd', 'Henley Arch Pty Ltd', true),
('Caddys Plumbing', 'Caddys Plumbing', true),
('Construction Zone', 'Construction Zone', true),
('Entracon', 'Entracon', true),
('Ken Basset', null, true),
('Australian Decommissioning Services Pty Ltd', 'Australian Decommissioning Services Pty Ltd', true),
('Ardor Group', 'Ardor Group', true),
('Billings Long Pty Ltd', 'Billings Long Pty Ltd', true),
('Brendan', null, true),
('Advanced Cranes', 'Advanced Cranes', true),
('Michael', null, true),
('Johns Lyng Group', 'Johns Lyng Group', true),
('McDonald''s Australia Limited', 'McDonald''s Australia Limited', true),
('McCorkell Constructions', 'McCorkell Constructions', true),
('Lorden Vella', 'Lorden Vella', true),
('Hume City Council', 'Hume City Council', true),
('JRL Building Group', 'JRL Building Group', true),
('Mirvac Home Builders (VIC) Pty Limited', 'Mirvac Home Builders (VIC) Pty Limited', true),
('MM Built Group', 'MM Built Group', true),
('Landart Landscapes', 'Landart Landscapes', true),
('LSR Construction Group', 'LSR Construction Group', true),
('Nash Constructions Pty Ltd', 'Nash Constructions Pty Ltd', true),
('Melbcon Pty Ltd', 'Melbcon Pty Ltd', true),
('Hunter Carlson Pty Ltd', 'Hunter Carlson Pty Ltd', true),
('Nillumbik Shire Council', 'Nillumbik Shire Council', true),
('Luxton Homes', 'Luxton Homes', true),
('Matthew Apollonio', null, true),
('P & A Mina & Sons', 'P & A Mina & Sons', true),
('Lincoln Park Holdings Pty Ltd', 'Lincoln Park Holdings Pty Ltd', true),
('J.J.Richards Engineering', 'J.J.Richards Engineering', true),
('Lauber Build', 'Lauber Build', true),
('Lowther Builders', 'Lowther Builders', true),
('John AfifBas', null, true),
('Nero Living', 'Nero Living', true),
('Longview Property', 'Longview Property', true),
('Minicon Construction Pty Ltd', 'Minicon Construction Pty Ltd', true),
('Chris Hughes', null, true),
('Iggy Walsh', null, true),
('Northern Valley Constructions', 'Northern Valley Constructions', true),
('L Apted & Sons', 'L Apted & Sons', true),
('Mees Bus Lines', 'Mees Bus Lines', true),
('Hitch Group Pty Ltd', 'Hitch Group Pty Ltd', true),
('Pivot Construction Group Pty Ltd', 'Pivot Construction Group Pty Ltd', true),
('Mundy Plumbing', 'Mundy Plumbing', true),
('JCM Builders', 'JCM Builders', true),
('Kombine Pty Ltd', 'Kombine Pty Ltd', true),
('Joscon Developments', 'Joscon Developments', true),
('MBO Constructions', 'MBO Constructions', true),
('Lindsay Transport', 'Lindsay Transport', true),
('Metro Air', 'Metro Air', true),
('Bill Panagiotopoulos', null, true),
('Mainbrace Constructions', 'Mainbrace Constructions', true),
('Insitu Group Pty Ltd', 'Insitu Group Pty Ltd', true),
('Phillip Kiriakidis', null, true),
('Hot Water Plant Maintenance Pty Ltd', 'Hot Water Plant Maintenance Pty Ltd', true),
('Striking Constructions Pty Ltd', 'Striking Constructions Pty Ltd', true),
('Striking Pools', 'Striking Pools', true),
('Verv Group Pty Ltd', 'Verv Group Pty Ltd', true),
('UpBuild', 'UpBuild', true),
('Poposki Constructions', 'Poposki Constructions', true),
('Strathridge Developments', 'Strathridge Developments', true),
('Saw Constructions', 'Saw Constructions', true),
('Uniquebuild (Aust) Pty Ltd', 'Uniquebuild (Aust) Pty Ltd', true),
('Q Industries Pty Ltd', 'Q Industries Pty Ltd', true),
('Tommy Tipper', 'Tommy Tipper', true),
('View Bank Homes', 'View Bank Homes', true),
('Power-Pac Generators', 'Power-Pac Generators', true),
('Rocky Vitacca', null, true),
('Third Rock Partners Pty Ltd', 'Third Rock Partners Pty Ltd', true),
('Uni Pro Painting', 'Uni Pro Painting', true),
('Son Builders', 'Son Builders', true),
('Mark Portman', null, true),
('STAN.BUILT PTY LTD', 'STAN.BUILT PTY LTD', true),
('Surefire Management Group Pty Ltd', 'Surefire Management Group Pty Ltd', true),
('STAARK', 'STAARK', true),
('Schultz Capital', 'Schultz Capital', true),
('Stecher Agricultural Services', 'Stecher Agricultural Services', true),
('Rob Roy', null, true),
('Reed Builders', 'Reed Builders', true),
('Simford Welding Services', 'Simford Welding Services', true),
('Shape Homes', 'Shape Homes', true),
('Graeme Stevens', null, true),
('PROFLOW Plumbing & Drainage', 'PROFLOW Plumbing & Drainage', true),
('Total Construction', 'Total Construction', true),
('Wide Open Constructions', 'Wide Open Constructions', true),
('Rivergum Homes', 'Rivergum Homes', true),
('Romar Group Pty Ltd', 'Romar Group Pty Ltd', true),
('James Wissell', null, true)
ON CONFLICT DO NOTHING;

-- Confirm import
SELECT COUNT(*) as total_customers FROM customers;
