// Mobile lint config (item N3). Before this, mobile/ had no lint tooling at all
// — no script, no dependency, no config — and the web config ignores `mobile/**`
// by name. Two dead `eslint-disable-next-line` directives already sat in the
// tree for a linter that would never read them.
//
// WHY IT IS WORTH HAVING HERE SPECIFICALLY. This project's recurring defect is
// the discarded async result: a promise whose rejection nobody handles, or a
// `{ error }` nobody reads. It has produced a clock-in that recorded no time, an
// RLS-denied edit reported as saved, a storage delete that kept the file, an
// invoice edit that destroyed every line. `@typescript-eslint/no-floating-
// promises` is the rule written for exactly that, and the repo already
// hand-rolls two substitutes for it (mobile's noSwallowedErrors.test.ts and the
// web's unchecked-mutations.test.ts).
//
// THE POLICY, decided before enabling rather than discovered afterwards:
//
//   error    things that are defects — an unhandled promise, an unused
//            eslint-disable directive (which is how the two dead ones above
//            survived), a genuinely unreachable branch.
//   warn     style and tidiness. Real signal, but failing a build on an unused
//            import teaches people to reach for --no-verify.
//
// CI runs `npm run lint`, which fails on errors and prints warnings. A warning
// count that only goes down is the same ratchet shape used elsewhere here.
//
// no-floating-promises needs type information, so the TS files get a
// type-aware parser pointed at tsconfig.json. That is slower; it is worth it
// for the one rule this whole file exists to enable.

const expoConfig = require("eslint-config-expo/flat");

module.exports = [
  ...expoConfig,

  {
    ignores: [
      "node_modules/**",
      // Generated by scripts/generate-powersync-schema.mjs. Linting a generated
      // file only ever produces noise the generator will overwrite.
      "lib/powersync/schema.ts",
      // Native projects, regenerated by prebuild and gitignored anyway.
      "android/**",
      "ios/**",
      ".expo/**",
      // This file is CommonJS (module.exports, __dirname). Linting it under the
      // ESM defaults reports __dirname as undefined, which is a fact about the
      // config's own parsing rather than about the code.
      "eslint.config.js",
    ],
  },

  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      // THE RULE THIS FILE EXISTS FOR — and the reason it is "warn" today.
      //
      // It finds 75 instances on first run, and they are NOT trivially
      // fixable. Almost all are a fire-and-forget `load()` inside a useEffect,
      // and the obvious fix — prefixing `void` — would silence the rule while
      // leaving the defect: those load() bodies are `useCallback(async …)` with
      // no try/catch, and although supabase resolves { data, error } rather
      // than throwing, a NETWORK failure still rejects. Voiding them would
      // convert a lint error into an unhandled rejection, which is worse than
      // either.
      //
      // So they need reading one at a time, which is real work and not
      // something to rush behind a green tick. Set to "warn" with the count
      // pinned by `npm run lint` (--max-warnings), so the number can only go
      // DOWN. Raise this to "error" once it reaches zero.
      "@typescript-eslint/no-floating-promises": "warn",
      // A directive that no longer suppresses anything is a lie about the code,
      // and is how the two dead ones in this tree went unnoticed.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // An unescaped apostrophe in JSX renders correctly; the rule guards
      // against ambiguity, not breakage. Style, so a warning — consistent with
      // the policy above rather than an exception carved out to get to green.
      "react/no-unescaped-entities": "warn",
    },
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
  },

  {
    // Tests deliberately do things the app should not: require() inside a
    // jest.mock factory, unawaited promises handed to expect().rejects.
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];
